name: C++ CI (G++)

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Compile
      run: g++ -std=c++17 -Wall -Wextra -pedantic -Werror item.cpp document.cpp manager.cpp editor.cpp -o editor